language: java
jdk:
  - oraclejdk6

before_script:
  - ./prepare-travis.sh

notifications:
  irc:
    channels:
      - "irc.freenode.net#wikimedia-analytics"
    template:
      - "%{branch}/%{commit} (#%{build_number} by %{author}): %{message} %{build_url}"
    use_notice: false
    skip_join: false
